### ISSUE TITLE
div的高度是由什么决定的呢？

### ISSUE THREAD

**Issue by Tommywt** [Tommywt/blog#16]
- div的高度是有行高决定的。
- 默认行高的值是设计师设定的。
- 每种字体的行高度都不一样的。
- 内联元素与内联元素之间是存在间隔的
- `$nsb`( no break space )空格

```css
text-align:justrfy;(多行左右对齐)
```
[详情](https://github.com/Tommywt/demo/blob/master/%E5%A4%9A%E8%A1%8C%E6%96%87%E6%9C%AC%E5%AF%B9%E9%BD%90.html)

- 清除浮动。如果子元素都进行浮动，那么父元素就要清除浮动。

```css
.clearfix{
content:' ';
display:block;
clear:both;
}
```

什么是文档流？就是内联元素默认从左往右排版，当空间不足时，内联元素会另起一行从左往右排版。

```css
world-break:break-all;
```
